version: '3.7'

services:
  gameshq_api_db_test:
    image: postgres:10-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'gameshq_api_test'
      POSTGRES_PASSWORD: '*games-2021'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gameshq_api_db_test_network
volumes:
  postgres:

networks:
  gameshq_api_db_test_network:
